### ISSUE TITLE
Gratulálok, és köszönjük!

### ISSUE THREAD

**Issue by nagyrobi** [amaximus/fkf-garbage-collection#1]
Pont gondoltam arra pár hete hogy írni kéne egy bővítményt erre a célra.

Köszönjük!

**Comment by amaximus** [comment]
Köszi. Sajnos nincs rendes APIja, úgy hogy htmlt kellett birizgálni.

**Comment by nagyrobi** [comment]
Ja, én is úgy közelítettem volna meg.
Előbb-utóbb valszeg kötelező lesz minden közszolgáltatásra API-kat nyújtani.
