### ISSUE TITLE
Calendar integration

### ISSUE THREAD

**Issue by laszlojakab** [amaximus/fkf-garbage-collection#10]
It would be good if garbage collection dates could be integrated into native HA calendar. I think you should inherit from CalendarEventDevice instead of Entity.

**Comment by amaximus** [comment]
Thanks for bringing up the idea.
The solution is under testing and will release it soon (in couple of days).

**Comment by amaximus** [comment]
I just recently released the version (0.1.0) adding support for calendar integration.

Please update the component and get back to me with results.

**Comment by laszlojakab** [comment]
Any hint for config yaml?

**Comment by amaximus** [comment]
What kind of configuration would you expect?

**Comment by laszlojakab** [comment]
Sorry, there no question here. I've just found the answer in updated readme :) Calendar works fine: 

![image](https://user-images.githubusercontent.com/6196882/104242600-b168e500-545f-11eb-9f6f-de3ed32174c4.png)

Is it possible to translate "communal" and "selective" text to Hungarian?

**Comment by laszlojakab** [comment]
As I know calendar entity can only "show" one all day event. What happens when selective and communal garbage collection happens on the same day? Shouldn't be there two separate calendars for them?

**Comment by amaximus** [comment]
When both types are to be collected on the same day, 'both' will be displayed (as per attached screenshot).
![screenshot-2021 01 11-23_17_21](https://user-images.githubusercontent.com/2511168/104245489-a49ac000-5464-11eb-9b62-10ae3a8a0ce4.png)

**Comment by amaximus** [comment]
There is however a bug in adding events to the calendar that I will fix in the coming days.

**Comment by amaximus** [comment]
Support for Hungarian translation on garbage type in calendar entries added in newest version 0.2.0.

Please update and get back to me with results.

FYI: the bug in adding events to the calendar is not fixed yet.

**Comment by laszlojakab** [comment]
Hungarian translation is working fine. Thanks!

**Comment by amaximus** [comment]
Thanks for confirmation.
