### ISSUE TITLE
Green waste collection day parsing

### ISSUE THREAD

**Issue by kovlo** [amaximus/fkf-garbage-collection#11]
There are districts, where the green waste collection day depends on the address location, the collection in those districts is distributed for the several weekdays:

 9  https://www.fkf.hu/kerti-zoldhulladek-korzetek-iv-kerulet
10 https://www.fkf.hu/kerti-zoldhulladek-korzetek-x-kerulet
14 https://www.fkf.hu/kerti-zoldhulladek-korzetek-xiv-kerulet
15 https://www.fkf.hu/kerti-zoldhulladek-korzetek-xv-kerulet
16 https://www.fkf.hu/kerti-zoldhulladek-korzetek-xvi-kerulet
17 https://www.fkf.hu/kerti-zoldhulladek-korzetek-xvii-kerulet
18 https://www.fkf.hu/kerti-zoldhulladek-korzetek-xviii-kerulet
19 https://www.fkf.hu/kerti-zoldhulladek-korzetek-xix-kerulet
20 https://www.fkf.hu/kerti-zoldhulladek-korzetek-xx-kerulet
21 https://www.fkf.hu/kerti-zoldhulladek-korzetek-xxi-kerulet
22 https://www.fkf.hu/kerti-zoldhulladek-korzetek-xxiii-kerulet

Currently the first day of a district's list is displayed in HA.

The solution might be challenging, as the color squares near the days are stored in images, and the polygons for the day are colored on a custom google map layer.

Two solution ideas:
1. Ask FKF for a better data/API...
2. Merge the green waste collection maps (via kml export?) to a common map and query the regions using the address - if it is possible.

**Comment by amaximus** [comment]
Thanks for the remark.
I was aware of some districts handling green garbage collection in a different way.
Unfortunately neither solutions would work:

1. FKF hasn't implemented a decent API. I don't see them providing public service with a future-proof vision.
2. The regions in the KML are a set of polygons, which is not an exact definition of data: often the other side of the road is out of the polygon while most probably they collect the green garbage from there too.

Until there is no exact data based on address (like for non-green garbage) or even preferably a decent API, I doubt I'll put the effort in handling this exception on green garbage collection.

Feel free to come up with a solution in a pull request. I'll be happy to review it and include it if it works.
