### ISSUE TITLE
Certificate verification error

### ISSUE THREAD

**Issue by myselfhostedhome** [amaximus/fkf-garbage-collection#13]
I receive the following error message when setting up the sensor:

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.fkf.hu:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')]

fkf changed its SSL cert recently issued by e-Szigno, I am not sure if this has anything to do with the above issue though.

**Comment by tjandras** [comment]
I had the same issue, but I had some restarts during today, and now it seems to be working again. I'm not what happened.

**Comment by amaximus** [comment]
Thanks for the heads-up, SSL connections to fkf.hu indeed failed.

It seems they fixed the certificate by now so https connections are ok.
