### ISSUE TITLE
Wrong and few dates.

### ISSUE THREAD

**Issue by ahkaroly** [amaximus/fkf-garbage-collection#16]
It’s only shown me a date since the last update, and that’s not well. I've already uninstalled the extension and reinstalled it. Unfortunately, I didn't realize what could be wrong. Do you have any ideas?

Thanks for the help!

https://horvathkaroly.hu/fkf_1.png
https://horvathkaroly.hu/fkf_2.png

**Comment by amaximus** [comment]
0.4.2 fixes the issue.

Please update the custom component and get back to me with results.

**Comment by ahkaroly** [comment]
Working perfectly. Thanks for this very fast fix! :)
