### ISSUE TITLE
The sensor state gets 'unknown' 

### ISSUE THREAD

**Issue by done7k** [amaximus/fkf-garbage-collection#19]
I see the integration updates sensor once per hour. But if for some reason it could not update the sensor it stays as 'unknown' till the next refresh (actually, only two 'next' fields are at 'null', the rest are not updated, see below). Also, I could not find any error message in log for this unsuccessful update event. My router is usually off during night and I see corresponding connectivity issues in log for this period. But this issue occurred during day, when the internet is on and no log msg, maybe there is another bug?

`items: 6
in0: 1
day0: Friday
date0: 2022.01.07
garbage0: communal
in1: 8
day1: Friday
date1: 2022.01.14
garbage1: communal
in2: 14
day2: Thursday
date2: 2022.01.20
garbage2: selective
in3: 15
day3: Friday
date3: 2022.01.21
garbage3: communal
in4: 22
day4: Friday
date4: 2022.01.28
garbage4: communal
in5: 29
day5: Friday
date5: 2022.02.04
garbage5: communal
current: current
next_communal_days: null
next_selective_days: null
calendar_lang: en
provider: Data provided by fkf.hu
icon: mdi:trash-can-outline
friendly_name: fkf_garbage_schedule`

**Comment by amaximus** [comment]
Connection errors are logged on debug level (see [1], [2] and [3]).
I might re-consider moving the log level of connection errors to warning in the next release.

[1] https://github.com/amaximus/fkf-garbage-collection/blob/master/custom_components/fkf-garbage-collection/sensor.py#L157
[2] https://github.com/amaximus/fkf-garbage-collection/blob/master/custom_components/fkf-garbage-collection/sensor.py#L193
[3] https://github.com/amaximus/fkf-garbage-collection/blob/master/custom_components/fkf-garbage-collection/sensor.py#L214
