### ISSUE TITLE
Log of sensor

### ISSUE THREAD

**Issue by zbeez** [amaximus/fkf-garbage-collection#2]
Hi amaximus,

tried to implement your sensor and card...but log shows the following:
Log Details (WARNING)
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:284
First occurred: 9:52:47 PM (1 occurrences)
Last logged: 9:52:47 PM

Updating state for sensor.fkf_my_schedule (<class 'custom_components.fkf_garbage_collection.sensor.FKFGarbageCollectionSensor'>) took 2.034 seconds. Please report it to the custom component author.

Card sadly doesn't even appear. Is there a way to solve this?
Would be glad for any help here.
Btw. looks beautiful, can't wait to make it work. :-)

**Comment by amaximus** [comment]
Hi zbeez,

could you please check in the Developer Tools that the sensor appears and has attributes?
Please also note that I pushed an update this afternoon (having issues with the sensor update).
Once you have the sensor working, please paste your card config from ui-lovelace.yaml to be able investigate the issue.

**Comment by zbeez** [comment]
All good. It works. Seems that the update helped. Didn't have the time to check it until now. 
I made my own card with the entity but in the standard UI config, not in the yaml mode. One additional question here: How can I address selective specifically, because only one state is dropped? ...is there a way to have to different states for the same sensor?
The sensor itself drops both one after another.

**Comment by amaximus** [comment]
The state of the sensor is the number of days till the first upcoming garbage collection.
All the other information go into attributes. You can, however have template sensors filtering on specific attribute fields.

**Comment by zbeez** [comment]
Hmmm...ok...I'm still a noob here. :-D Just having my home automation hobby and try to get everything running on my Raspberry, then your marvelous idea hit my eye and told myself: I need to have that. :-)
But I'll try the filter. Thank you very much for your input.
