### ISSUE TITLE
Cannot change language to Hungarian

### ISSUE THREAD

**Issue by varmik18** [amaximus/fkf-garbage-collection#21]
Hi amaximus,

I couldn't set the calendar language to Hungarian.
Please see below my config.

```
platform: fkf_garbage_collection
name: 'fkf'
zipcode: !secret fkf_zipcode
publicplace: !secret fkf_publicplace
housenr: !secret fkf_housenr
offsetdays: 1
calendar: false
calendar_lang: hu
green: true
greencolor: rozsaszin
```
fkf-garbage-collection-card shows weekdays in English.

Could you give me a hint how to resolve this issue?
Thank you,
varmik

**Comment by amaximus** [comment]
Please note that this integration does not provide language support (except for calendar entries, when enabled).

The associated card (https://github.com/amaximus/fkf-garbage-collection-card) provides language support based on browser's language, but you can also use other things to display FKF garbage collection information (e.g. I'm using custom button card which has a great flexibility).
Usually display related parameters (e.g. display information in a specific language) are handled on the frontend side, while the integrations run on the backend.
