### ISSUE TITLE
next_green_days attribute should be null when it is unknown

### ISSUE THREAD

**Issue by laszlojakab** [amaximus/fkf-garbage-collection#24]
Currently the next_green_days attribute is `0` when it integration fails to fetch data:

![image](https://user-images.githubusercontent.com/6196882/203626938-90115760-6a21-4bee-8820-9287feca0d87.png)

It is missleading, it should be null as `next_communal_days` or `next_selective_days`.

**Comment by amaximus** [comment]
I recently pushed a new release fixing this issue.

Please update the integration, test it and get back to me with results.

**Comment by amaximus** [comment]
Any update on this?

**Comment by laszlojakab** [comment]
There is no green garbage collection since 2022/12/01 in our area and now `next_green_days` attribute as well.
![image](https://user-images.githubusercontent.com/6196882/213546369-86cac7b6-ece4-4a02-8d94-5a8d0921a5bb.png)

**Comment by amaximus** [comment]
Just pushed a new release addressing this issue.

Please update the integration and get back to me with results.

**Comment by laszlojakab** [comment]
It looks OK now:
![image](https://user-images.githubusercontent.com/6196882/213809609-62d80d23-3134-45e9-8642-78dd12570a96.png)
