### ISSUE TITLE
card ok but no data

### ISSUE THREAD

**Issue by redlingg** [amaximus/fkf-garbage-collection#25]
type: custom:fkf-garbage-collection-card
card_mod:
  style: |
    ha-card {
      background: lightgrey;
      box-shadow: none;
      color: red 
    }
entity: sensor.fkf_my_schedule
title: Kuka
icon_size: 35px

**Comment by redlingg** [comment]
working…..took about an hour to appear…..

**Comment by redlingg** [comment]
Not clear how it should work. When I check the config, it says everything is ok. Now there is nothing on the card (no data). The garbage was collected today (both). It says in the descreption that no housenumber or street name is needed for Budaors but if I dont put it, it gives an error code. This is the sensor config:

 - platform: fkf_garbage_collection
    name: 'fkf_my_schedule'
    publicplace: "Tavasz"
    zipcode: '2040'
    housenr: '1'

the card config is already above.

**Comment by amaximus** [comment]
So the minimal sensor definition should be:
```
(ha_venv3_9) pi@raspberrypi:~/homeassistant_test/sensors $grep -v "^#" fkf_budaors.yaml
platform: fkf_garbage_collection
name: 'fkf_budaors'
publicplace: 'Tavasz utca'
housenr: '1'
city: 'Budaörs'
(ha_venv3_9) pi@raspberrypi:~/homeassistant_test/sensors $
```
in which case the data is returned as expected:
![budaors](https://user-images.githubusercontent.com/2511168/214260118-c00bd0eb-53fa-4a6a-87b4-47efadaab1ff.PNG)

which shows the same as the FKF site:
![budaors_fkf](https://user-images.githubusercontent.com/2511168/214260419-f4bc946b-1bdb-47b8-a85a-c84ca12796a5.PNG)

**Comment by amaximus** [comment]
But you gave me an idea to get rid of the new ```city``` parameter and identify Budaörs per zipcode.

**Comment by redlingg** [comment]
Joy and happyness! Thanks :)
