### ISSUE TITLE
Compatibility with 2023.6

### ISSUE THREAD

**Issue by csabatth** [amaximus/fkf-garbage-collection#28]
Szia Attila,

Nem tudom jelezte-e már valaki, de nekem úgy tunik, hogy a 2023.6-os update "eltörte" az integrációt, 5.4-re történö visszaállás után ismét muködik.

Köszönöm ha foglalkozol vele.

Udv.

Csaba

**Comment by amaximus** [comment]
Szia Csaba,

nekem működik. A legutóbbi verzió 0.8.0.
Kérhetnék egy szenzor konfigurációt? (házszámnak írhatsz más létező számot).

Köszi.

**Comment by csabatth** [comment]
Szia,

A sokadik újratelepítés után muködik ismét a 6.2-vel is, olyan mintha az elözö verzió maradt volna meg valamiért a könyvtárban.

Köszönöm!

Udv.

Csaba
