### ISSUE TITLE
2024.2.5 HA no data probléma

### ISSUE THREAD

**Issue by burkisha** [amaximus/fkf-garbage-collection#30]
sensor:
  - platform: fkf_garbage_collection
    name: "kukat_kivinni"
    zipcode: "1141"
    publicplace: "Vágsellye utca"
    housenr: "4"

kártya
type: custom:fkf-garbage-collection-card
entity: sensor.kukat_kivinni
icon_size: 35px
items_number: 1
hide_wday: true
due_1_color: red
hide_before: 1

**Comment by amaximus** [comment]
Az adatok símán ott vannak:
```
(ha_venv3_12) pi@raspberrypi:~/homeassistant_test $cat sensors/fkf_iv.yaml
platform: fkf_garbage_collection
name: 'fkf_iv'
zipcode: '1141'
publicplace: 'Vágsellye utca'
housenr: '4'
calendar: false
calendar_lang: hu
green: false
greencolor: lila
(ha_venv3_12) pi@raspberrypi:~/homeassistant_test $curl -H @hass_header.txt http://192.168.1.156:9000/api/states/sensor.fkf_iv
{"entity_id":"sensor.fkf_iv","state":"0","attributes":{"items":7,"in0":0,"day0":"Tuesday","date0":"2024.03.05","garbage0":"communal","in1":3,"day1":"Friday","date1":"2024.03.08","garbage1":"selective","in2":7,"day2":"Tuesday","date2":"2024.03.12","garbage2":"communal","in3":14,"day3":"Tuesday","date3":"2024.03.19","garbage3":"communal","in4":21,"day4":"Tuesday","date4":"2024.03.26","garbage4":"communal","in5":28,"day5":"Tuesday","date5":"2024.04.02","garbage5":"communal","in6":31,"day6":"Friday","date6":"2024.04.05","garbage6":"selective","current":"current","next_communal_days":0,"next_green_days":null,"next_selective_days":3,"calendar_lang":"hu","provider":"Data provided by fkf.hu","icon":"mdi:trash-can-outline","friendly_name":"fkf_iv"},"last_changed":"2024-03-05T10:35:09.679889+00:00","last_updated":"2024-03-05T10:35:09.679889+00:00","context":{"id":"01HR72WXFFNJ1Q8R4HRSPNCKZ8","parent_id":null,"user_id":null}}
(ha_venv3_12) pi@raspberrypi:~/homeassistant_test $
```
Nézd meg a home-assistant.log-ot, hogy nem dobott valamilyen pythonos hibát?
Esetleg állítsd az integrációt debug-ba a configuration.yaml-ban, indítsd újra a HA-t és nézd meg a home-assistant.log-ot:
```
logger:
  logs:
    custom_components.fkf_garbage_collection.sensor: debug
```

**Comment by burkisha** [comment]
ezt találtam:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:599
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 4 March 2024 at 18:39:58 (1 occurrences)
Last logged: 4 March 2024 at 18:39:58

fkf_garbage_collection: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 603, in _request
    resp = await req.send(conn)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 713, in send
    await writer.write_headers(status_line, self.headers)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1259, in async_device_update
    await self.async_update()
  File "/config/custom_components/fkf_garbage_collection/sensor.py", line 412, in async_update
    fkfdata = await async_get_fkfdata(self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fkf_garbage_collection/sensor.py", line 205, in async_get_fkfdata
    async with self._session.get(url, timeout=HTTP_TIMEOUT) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 617, in _request
    raise ClientOSError(*exc.args) from exc
aiohttp.client_exceptions.ClientOSError: Cannot write to closing transport

**Comment by amaximus** [comment]
A frissen felküldött 0.8.2 javítja ezt a hibát. Gyakorlatilag minden (óránkénti) frissítéskor új kliens session-t nyit. Igy egy rég óta futó  HA esetén, a session.close() nem okoz majd kapcsolódási hibát.

Kérlek frissítsd az integrációt, indítsd újra a HA-t és teszteld egy-két napig (amúgy is óránként frissít). Majd szólj vissza az eredményről.

**Comment by burkisha** [comment]
az a fura, hogy az éles rendszeremen nem javult meg, de a teszt környezetben igen

**Comment by amaximus** [comment]
Mit add vissza a `curl https://www.fkf.hu/hulladeknaptar` a HA szerverről indítva?
A fenti escape-ek függetlenek ettől.

**Comment by burkisha** [comment]
ekkora guru azért nem vagyok, de egy terminal ablakba bemásolva egy nem túl rövid html doksi lett az eredmény

**Comment by burkisha** [comment]
verziók szempontjából minden uaz, kivéve a vas. éles rendszer egy odroid, teszt pedig egy vmware vm. de mind a kettő HAOS telepítés.
most külön megnéztem aboutban, mind a 4 szoftver komponens uaz a verzió, és mind a kettőn a 0.82 van

**Comment by burkisha** [comment]
most még kipróbálom az fkf leszed, restart, fkf vissza, restart

**Comment by burkisha** [comment]
2024-03-05 17:11:00.617 DEBUG (MainThread) [custom_components.fkf_garbage_collection.sensor] Connection error to fkf.hu
2024-03-05 17:11:00.617 DEBUG (MainThread) [custom_components.fkf_garbage_collection.sensor] Fetch info for 1141/Vágsellye---utca/4:

**Comment by burkisha** [comment]
![image](https://github.com/amaximus/fkf-garbage-collection/assets/116830546/86474a5e-6131-40ac-80cd-9fc08864b606)

**Comment by amaximus** [comment]
Minden jel arra utal, hogy vagy neked vagy az fkf.hu-nak vannak hálózati problémái.

**Comment by burkisha** [comment]
igen, látom..... csak közben én nem tapasztalok semmi hálózati problémát itthon, nem is változtattam a hálózati beállításokon jó ideje (unifi rendszer). HA is vezetékes kapcsolaton, statikus IP, routerben is rögzítve. Meg hát működött is az FKF több mint egy évig

**Comment by burkisha** [comment]
![image](https://github.com/amaximus/fkf-garbage-collection/assets/116830546/1f9f75f5-9e36-4d16-9c49-be5627f82fac)
![image](https://github.com/amaximus/fkf-garbage-collection/assets/116830546/778e35ad-f445-47d5-93dc-ec780e089132)

**Comment by burkisha** [comment]
és magához tért
![image](https://github.com/amaximus/fkf-garbage-collection/assets/116830546/dbec6806-29f6-4fcf-ac86-516e8d7618c5)

**Comment by amaximus** [comment]
Nincs mit.
